### ISSUE TITLE
Problem with running the examples (Renderer)

### ISSUE THREAD

**Issue by ronen85** [liruiw/OMG-Planner#12]
Hello, 
When running `python -m real_world.trial -s script.txt -v -f kitchen0` i get the following error:

```
loaded one task script: script.txt
target: ['003_cracker_box']
place delta poses: [[-0.45, 0.0, 0.0, 0.0], [0.1, 0.35, -0.6, 1.0]]
Setting up env...
env init time: 0.132
['025_mug', '004_sugar_box', 'kitchen_handle', 'kitchen_sektion_top_two_glass', 'kitchen_handle', 'kitchen_handle', 'kitchen_front_vertical_left', 'kitchen_sektion_top_three', 'kitchen_handle', 'kitchen_sektion_bottom_two_drawers', 'kitchen_front_vertical_right', 'kitchen_drawer_large', 'kitchen_front_vertical_right', 'kitchen_sektion_bottom_cabinet', 'kitchen_drawer_large', 'kitchen_walls', 'kitchen_handle', '003_cracker_box']
populate scene time: 0.217
025_mug IK init time: 0.384, failed_ik: 5, goal set num: 104/30
004_sugar_box IK init time: 0.791, failed_ik: 47, goal set num: 312/100
003_cracker_box IK init time: 0.884, failed_ik: 77, goal set num: 70/100
025_mug IK FOUND collision-free goal num 37/37/37/65
004_sugar_box IK FOUND collision-free goal num 43/43/43/321
003_cracker_box IK FOUND collision-free goal num 35/35/35/70
Setting up renderer...
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
Unable to initialize EGL
Command '['/home/nir1tv/projects/OMG-Planner/real_world/../ycb_render/build/test_device', '2']' returned non-zero exit status 1.
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
Unable to initialize EGL
Command '['/home/nir1tv/projects/OMG-Planner/real_world/../ycb_render/build/test_device', '3']' returned non-zero exit status 1.
number of devices found 5
Loaded EGL 1.5 after reload.
Renderer init time: 0.599
Traceback (most recent call last):
  File "/home/nir1tv/miniconda3/envs/gaux/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nir1tv/miniconda3/envs/gaux/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nir1tv/projects/OMG-Planner/real_world/trial.py", line 523, in <module>
    main()
  File "/home/nir1tv/projects/OMG-Planner/real_world/trial.py", line 363, in main
    scene.reset()
  File "/home/nir1tv/projects/OMG-Planner/real_world/../omg/core.py", line 486, in reset
    self.setup_renderer()
  File "/home/nir1tv/projects/OMG-Planner/real_world/../omg/core.py", line 769, in setup_renderer
    renderer.load_objects(models, scale=resize)
  File "/home/nir1tv/projects/OMG-Planner/real_world/../ycb_render/ycb_renderer.py", line 1164, in load_objects
    scenes, textures = self.parallel_assimp_load(obj_paths, scale)
  File "/home/nir1tv/projects/OMG-Planner/real_world/../ycb_render/ycb_renderer.py", line 1116, in parallel_assimp_load
    for i in range(len(mesh_files))]
  File "/home/nir1tv/projects/OMG-Planner/real_world/../ycb_render/ycb_renderer.py", line 1116, in <listcomp>
    for i in range(len(mesh_files))]
  File "/home/nir1tv/projects/OMG-Planner/real_world/../ycb_render/ycb_renderer.py", line 54, in load_mesh_single
    return recursive_load(scene.rootnode, [], [], [], [], offset, scale, [[], [], []])
  File "/home/nir1tv/projects/OMG-Planner/real_world/../ycb_render/ycb_renderer.py", line 156, in recursive_load
    child, vertices, faces, materials, texture_paths, offset, scale, repeated
  File "/home/nir1tv/projects/OMG-Planner/real_world/../ycb_render/ycb_renderer.py", line 107, in recursive_load
    mat_diffuse = np.array(mat.properties["diffuse"])[:3]
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```
When I checked `mat.properties["diffuse"]` in debug mode, it was 0 (expecting a list/array).

**Comment by liruiw** [comment]
It seems to be a pyassimp version problem, please check out this https://github.com/NVlabs/PoseCNN-PyTorch/issues/4 and do pip install pyassimp==4.1.3.

**Comment by ronen85** [comment]
First, thank you for your help!

Using the PoseRBPF repository, I managed to set up and run the ycb_renderer (after downgrading pyassimp to 4.1.3 version and following the instructions [here](https://github.com/NVlabs/PoseRBPF/blob/master/ycb_render/README.md)).

In PoseRBPF/ycb_render, I ran ycb_renderer.py without any errors, so I think the opengl/nvidia on my machine are fine.

In digging through your *ycb_renderer.py* file, I found an error with the load function that results in an IndexError when the `recursive_load` function is called.

I don't know why, but the material properties described in the DAE file are not passed correctly to the  mat.properties dictionary.

This was tested on 2 different Ubuntu 20.04 machines with nvidia 2080 Ti GPU.

**Comment by liruiw** [comment]
I think the renderer in PoseRBPF repository does not load material property which might be the reason why you don't see the errors. I am not using Ubuntu 20.04. But from the link I provided above, maybe you could try building assimp version 4 from source and see if that helps.
